controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

billing_download:
    path: /billing/{id}/download
    controller: App\Controller\BillingController::download
